# GitHub Sponsors configuration
github: s1xt333n

# Ko-fi (optional - replace with your Ko-fi username if you have one)
# ko_fi: s1xt333n

# Buy Me A Coffee (optional - replace with your username if you have one)
# custom: ["https://www.buymeacoffee.com/s1xt333n"]

# Patreon (optional)
# patreon: s1xt333n

# Open Collective (optional)
# open_collective: s1xt333n
