# Repository Configuration for GitHub

name: Modern SaaS Animated
description: 🎭 Modern SaaS template with EPIC 6-layer floating circles animation featuring 180+ rotating portraits! The most mesmerizing animated SaaS template ever created! ✨
homepage: https://s1xt333n.github.io/modern-saas-animated

topics:
  - saas-template
  - animation
  - floating-circles
  - css-animation
  - modern-design
  - javascript
  - lead-generation
  - starter-kit
  - webapp
  - responsive
  - modern-ui
  - tailwindcss
  - authentication
  - real-time
  - business
  - sales-automation
  - admin-template
  - progressive-web-app
  - open-source
  - customizable
  - production-ready

social_preview_image: assets/images/social-preview.png

# GitHub Pages Configuration
pages:
  source:
    branch: main
    path: /

# Branch Protection Rules
branches:
  main:
    protection:
      required_status_checks:
        strict: true
        contexts:
          - continuous-integration
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      restrictions: null

# Issue Templates
issue_templates:
  - name: Bug Report
    description: Report a bug or issue
    labels:
      - bug
      - needs-triage
  - name: Feature Request
    description: Suggest a new feature
    labels:
      - enhancement
      - feature-request
  - name: Template Usage Question
    description: Ask about using this template
    labels:
      - question
      - template-usage

# Labels
labels:
  - name: template
    color: '#7B68EE'
    description: Related to template functionality
  - name: crm
    color: '#FF6B6B'
    description: CRM-related features
  - name: firebase
    color: '#FFA500'
    description: Firebase integration
  - name: ui-enhancement
    color: '#4ECDC4'
    description: User interface improvements
  - name: documentation
    color: '#95A5A6'
    description: Documentation updates
  - name: good-first-issue
    color: '#7057FF'
    description: Good for newcomers
